# Generated by Django 4.1.7 on 2023-07-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_remove_product_suggestions_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='suggestion_name',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_name',
            field=models.ManyToManyField(blank=True, to='suggestions.suggestion'),
        ),
    ]
