# Generated by Django 4.1.7 on 2023-07-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_remove_suggestion_suggestion_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suggestions',
            field=models.ManyToManyField(blank=True, to='suggestions.product'),
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
