# Generated by Django 4.1.7 on 2023-07-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0012_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
