# Generated by Django 4.1.7 on 2023-07-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_validation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='code',
        ),
        migrations.AddField(
            model_name='promocode',
            name='coupon_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocode',
            name='minimum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
