# Generated by Django 4.1.7 on 2023-07-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_validation', '0002_remove_promocode_code_promocode_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
