# Generated by Django 4.1.7 on 2023-07-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_validation', '0003_promocode_end_date_promocode_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
