# Generated by Django 4.1.7 on 2023-07-16 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo_validation', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='coupon_code',
            new_name='coupon_name',
        ),
        migrations.AddField(
            model_name='product',
            name='coupon_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo_validation.promocode'),
        ),
    ]
