# Generated by Django 4.1.7 on 2023-07-16 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo_validation', '0005_rename_coupon_code_promocode_coupon_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='coupon_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promo_validation.coupon'),
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
